parameters:
  vulnerability_weightingFile:        '%kernel.project_dir%/src/BeneficiaryBundle/Resources/config/vulnerability/weighting_example.csv'
  vulnerability_scoringFileTemplate:  '%kernel.project_dir%/src/BeneficiaryBundle/Resources/config/vulnerability/scoring_<<COUNTRY>>.csv'