imports:
    - { resource: parameters.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BeneficiaryBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    BeneficiaryBundle\Utils\APIImportService:
        public: true
    BeneficiaryBundle\Utils\BeneficiaryService:
        public: true
    BeneficiaryBundle\Utils\CountrySpecificService:
        public: true
    BeneficiaryBundle\Utils\CommunityService:
        public: true
    BeneficiaryBundle\Utils\HouseholdCSVService:
        public: true
    BeneficiaryBundle\Utils\HouseholdExportCSVService:
        public: true
    BeneficiaryBundle\Utils\HouseholdService:
        public: true
    BeneficiaryBundle\Utils\InstitutionService:
        public: true
    BeneficiaryBundle\Utils\Mapper\CSVToArrayMapper:
        public: false

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    RA\RequestValidatorBundle\RequestValidator\RequestValidator:
        alias: request_validator

    beneficiary.repository:
        alias: BeneficiaryBundle\Repository\BeneficiaryRepository

    BeneficiaryBundle\Repository\BeneficiaryRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BeneficiaryBundle\Entity\Beneficiary

    BeneficiaryBundle\Mapper\CommunityMapper:
        public: true

    BeneficiaryBundle\Mapper\InstitutionMapper:
        public: true

    BeneficiaryBundle\Mapper\AddressMapper:
        public: true

    BeneficiaryBundle\Mapper\NationalIdMapper:
        public: true

    BeneficiaryBundle\Mapper\BeneficiaryMapper:
        public: true

    BeneficiaryBundle\Mapper\AssistanceMapper:
        public: true

    BeneficiaryBundle\Mapper\PhoneMapper:
        public: false

    BeneficiaryBundle\Mapper\PersonMapper:
        public: false

    BeneficiaryBundle\Mapper\ProfileMapper:
        public: false

    BeneficiaryBundle\Model\Vulnerability\Resolver:
        arguments:
            - "%vulnerability_weightingFile%"
            - "%vulnerability_scoringFileTemplate%"
            - "@BeneficiaryBundle\\Repository\\BeneficiaryRepository"

    beneficiary.vulnerability_resolver:
        alias: BeneficiaryBundle\Model\Vulnerability\Resolver
        public: true


#######################################################################################
##                                      IMPORT                                       ##
#######################################################################################

    beneficiary.api_import_service:
        class: BeneficiaryBundle\Utils\APIImportService
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@service_container"
        public: true
        autowire: true

#######################################################################################
##                                        CSV                                        ##
#######################################################################################

    beneficiary.household_csv_service:
        class: BeneficiaryBundle\Utils\HouseholdCSVService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@BeneficiaryBundle\\Utils\\HouseholdService"
            - "@BeneficiaryBundle\\Utils\\BeneficiaryService"
            - "@beneficiary.csv_to_array_mapper"
            - "@service_container"
        public: true

    beneficiary.csv_to_array_mapper:
        class: BeneficiaryBundle\Utils\Mapper\CSVToArrayMapper
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    beneficiary.syria_file_to_template_mapper:
        class: BeneficiaryBundle\Utils\Mapper\SyriaFileToTemplateMapper
        autowire: true
        public: true

    household.activity_listerer:
        class: BeneficiaryBundle\Listener\HouseholdActivitySubscriber
        autowire: true
        tags:
            - { name: 'doctrine.event_subscriber', priority: 500 }
