imports:
    - { resource: parameters.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BeneficiaryBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    BeneficiaryBundle\Utils\:
        resource: '../../Utils'

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    RA\RequestValidatorBundle\RequestValidator\RequestValidator:
        alias: request_validator

    beneficiary.household_service:
        alias: BeneficiaryBundle\Utils\HouseholdService
        public: true

    beneficiary.institution_service:
        alias: BeneficiaryBundle\Utils\InstitutionService
        public: true

    beneficiary.repository:
        alias: BeneficiaryBundle\Repository\BeneficiaryRepository

    BeneficiaryBundle\Repository\BeneficiaryRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BeneficiaryBundle\Entity\Beneficiary

    BeneficiaryBundle\Mapper\CommunityMapper:
        public: true

    BeneficiaryBundle\Mapper\InstitutionMapper:
        public: true

    BeneficiaryBundle\Mapper\AddressMapper:
        public: true

    BeneficiaryBundle\Mapper\NationalIdMapper:
        public: true

    BeneficiaryBundle\Mapper\BeneficiaryMapper:
        public: true

    BeneficiaryBundle\Mapper\AssistanceMapper:
        arguments:
            - '@BeneficiaryBundle\Mapper\BeneficiaryMapper'
            - "@=service('doctrine.orm.entity_manager').getRepository('DistributionBundle:AssistanceBeneficiary')"
        public: true

    BeneficiaryBundle\Mapper\PhoneMapper:
        public: false

    BeneficiaryBundle\Mapper\PersonMapper:
        public: false

    BeneficiaryBundle\Mapper\ProfileMapper:
        public: false

    BeneficiaryBundle\Model\Vulnerability\Resolver:
        arguments:
            - "%vulnerability_weightingFile%"
            - "%vulnerability_scoringFileTemplate%"
            - "@beneficiary.repository"

    beneficiary.vulnerability_resolver:
        alias: BeneficiaryBundle\Model\Vulnerability\Resolver
        public: true


#######################################################################################
##                                      IMPORT                                       ##
#######################################################################################

    beneficiary.api_import_service:
        class: BeneficiaryBundle\Utils\APIImportService
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@service_container"
        public: true
        autowire: true


    beneficiary.khm_api_provider_idpoor:
        class: BeneficiaryBundle\Utils\ImportProvider\KHM\KHMIDPoorAPIProvider
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@validator"
            - "@service_container"


#######################################################################################
##                                        CSV                                        ##
#######################################################################################

    beneficiary.household_export_csv_service:
        class: BeneficiaryBundle\Utils\HouseholdExportCSVService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@export_csv_service"
        public: true

    beneficiary.household_csv_service:
        class: BeneficiaryBundle\Utils\HouseholdCSVService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@beneficiary.household_service"
            - Beneficiary\Utils\BeneficiaryService
            - "@beneficiary.csv_to_array_mapper"
            - "@service_container"
        public: true

    beneficiary.csv_to_array_mapper:
        class: BeneficiaryBundle\Utils\Mapper\CSVToArrayMapper
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    beneficiary.syria_file_to_template_mapper:
        class: BeneficiaryBundle\Utils\Mapper\SyriaFileToTemplateMapper
        autowire: true
        public: true

    household.activity_listerer:
        class: BeneficiaryBundle\Listener\HouseholdActivitySubscriber
        autowire: true
        tags:
            - { name: 'doctrine.event_subscriber', priority: 500 }
