rest_user:
    type: annotation
    resource: "@UserBundle/Resources/config/routing.yml"

rest_project:
    type: annotation
    resource: "@ProjectBundle/Resources/config/routing.yml"

rest_beneficiary:
    type: annotation
    resource: "@BeneficiaryBundle/Resources/config/routing.yml"

rest_distribution:
    type: annotation
    resource: "@DistributionBundle/Resources/config/routing.yml"

rest_reporting:
    resource: "@ReportingBundle/Resources/config/routing.yml"

rest_common:
    resource: "@CommonBundle/Resources/config/routing.yml"

rest_transaction:
    resource: "@TransactionBundle/Resources/config/routing.yml"

rest_voucher:
    resource: "@VoucherBundle/Resources/config/routing.yml"
