security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: id

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false

        # tester
        tester_initialize:
            pattern:    ^/api/wsse/initialize
            security:   false
        tester_salt:
            pattern:    ^/api/wsse/salt
            security:   false
        tester_login_app:
            pattern:    ^/api/wsse/login
            security:   false
        tester_vendor_salt:
            pattern:    ^/api/wsse/vendor-app/v1/salt
            security:   false
        tester_vendor_login_app:
            pattern:    ^/api/wsse/vendor-app/v1/login
            security:   false

        #WSSE
        wsse_secured:
            pattern:    ^/api/
            stateless:  true
            wsse:       true
            anonymous:  false
            methods:    [GET, PUT, POST, DELETE, OPTIONS]
            provider:   our_db_provider

    access_control:
        # Login
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

    access_decision_manager:
        strategy: unanimous


    role_hierarchy:
        ROLE_REPORTING:               [ROLE_REPORTING_READ, ROLE_REPORTING_WRITE]
        ROLE_PROJECT_MANAGEMENT:      [ROLE_PROJECT_MANAGEMENT_READ, ROLE_PROJECT_MANAGEMENT_WRITE, ROLE_PROJECT_MANAGEMENT_ASSIGN]
        ROLE_BENEFICIARY_MANAGEMENT:  [ROLE_BENEFICIARY_MANAGEMENT_READ, ROLE_BENEFICIARY_MANAGEMENT_WRITE]
        ROLE_USER_MANAGEMENT:         [ROLE_USER_MANAGEMENT_READ, ROLE_USER_MANAGEMENT_WRITE]
        ROLE_AUTHORISE_PAYMENT:       [ROLE_AUTHORISE_PAYMENT]
        # BMS Roles
        ROLE_READ_ONLY:               [ROLE_USER]
        ROLE_FIELD_OFFICER:           [ROLE_USER, ROLE_PROJECT_MANAGEMENT_READ, ROLE_PROJECT_MANAGEMENT_ASSIGN, ROLE_REPORTING_READ, ROLE_BENEFICIARY_MANAGEMENT_READ]
        ROLE_PROJECT_OFFICER:         [ROLE_USER, ROLE_PROJECT_MANAGEMENT_READ, ROLE_PROJECT_MANAGEMENT_ASSIGN, ROLE_REPORTING, ROLE_BENEFICIARY_MANAGEMENT]
        ROLE_PROJECT_MANAGER:         [ROLE_USER, ROLE_DISTRIBUTIONS_DIRECTOR, ROLE_PROJECT_MANAGEMENT, ROLE_REPORTING, ROLE_BENEFICIARY_MANAGEMENT, ROLE_AUTHORISE_PAYMENT, ROLE_USER_MANAGEMENT]
        ROLE_COUNTRY_MANAGER:         [ROLE_USER, ROLE_REPORTING_COUNTRY, ROLE_USER_MANAGEMENT, ROLE_PROJECT_MANAGEMENT, ROLE_REPORTING, ROLE_BENEFICIARY_MANAGEMENT_READ, ROLE_AUTHORISE_PAYMENT]
        ROLE_REGIONAL_MANAGER:        [ROLE_USER, ROLE_REPORTING_COUNTRY, ROLE_PROJECT_MANAGEMENT_READ, ROLE_REPORTING_READ, ROLE_BENEFICIARY_MANAGEMENT_READ]
        ROLE_ADMIN:                   [ROLE_VENDOR, ROLE_READ_ONLY, ROLE_FIELD_OFFICER, ROLE_PROJECT_OFFICER, ROLE_PROJECT_MANAGER, ROLE_COUNTRY_MANAGER, ROLE_REGIONAL_MANAGER]
        ROLE_VENDOR:                  [ROLE_USER]
        ROLE_ENUMERATOR:              [ROLE_USER, ROLE_PROJECT_MANAGEMENT_READ, ROLE_PROJECT_MANAGEMENT_ASSIGN, ROLE_BENEFICIARY_MANAGEMENT_READ]
