imports:
    - { resource: ../../src/BeneficiaryBundle/Resources/config/services.yml }
    - { resource: ../../src/DistributionBundle/Resources/config/services.yml }
    - { resource: ../../src/ProjectBundle/Resources/config/services.yml }
    - { resource: ../../src/UserBundle/Resources/config/services.yml }
    - { resource: ../../src/ReportingBundle/Resources/config/services.yml }
    - { resource: ../../src/CommonBundle/Resources/config/services.yml }
    - { resource: ../../src/TransactionBundle/Resources/config/services.yml }
    - { resource: ../../src/VoucherBundle/Resources/config/services.yml }
    - { resource: ../../src/NewApiBundle/Resources/config/services.yml }
