services:


#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    location_service:
        class: CommonBundle\Utils\LocationService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@request_validator"

    organization_service:
        class: CommonBundle\Utils\OrganizationService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@service_container"

    export_csv_service:
        class: CommonBundle\Utils\ExportService
        public: true

    pdf_service:
        class: CommonBundle\Utils\PdfService
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            
    log_service:
        class: CommonBundle\Utils\LogService
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_validator"

    CommonBundle\Mapper\LocationMapper:
        public: true

#######################################################################################
##                                     LISTENER                                      ##
#######################################################################################
    CommonBundle\Listener\RequestListener:
        arguments:
        - "@doctrine.orm.entity_manager"
        - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    CommonBundle\Listener\ResponseListener:
        arguments:
        - "@doctrine.orm.entity_manager"
        - "@service_container"
        tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    CommonBundle\InputType\RequestConverter:
        arguments:
            - '@validator'
        tags:
            - { name: request.param_converter, converter: input_types_converter }

    CommonBundle\Listener\LoggerSubscriber:
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }


#######################################################################################
##                                      FIXTURE                                      ##
#######################################################################################

    CommonBundle\DataFixtures\CountrySpecificFixtures:
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\DonorFixtures:
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\LocationFixtures:
        arguments:
            - "@kernel"
            - "@location_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\LocationTestFixtures:
        arguments:
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\ModalityFixtures:
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\ProjectFixtures:
        arguments:
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\UserFixtures:
        arguments:
            - "@fos_user.user_manager"
            - "@security.encoder_factory"
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\VulnerabilityCriterionFixtures:
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\BookletFixtures:
        arguments:
            - "@kernel"
            - "@voucher.booklet_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\Beneficiaries\BeneficiaryBookletFixtures:
        arguments:
            - "@kernel"
            - "@voucher.booklet_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\BeneficiaryTestFixtures:
        arguments:
            - "@kernel"
            - "@beneficiary.household_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\Beneficiaries\InstitutionFixture:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@beneficiary.institution_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\Beneficiaries\CommunityFixture:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@beneficiary.community_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\AssistanceFixtures:
        arguments:
            - "@kernel"
            - "@distribution.assistance_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\AssistanceValidationFixtures:
        arguments:
            - "@kernel"
            - "@distribution.assistance_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\Beneficiaries\AssistanceBeneficiaryFixtures:
        arguments:
            - "@kernel"
            - "@distribution.assistance_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\VoucherPurchaseFixtures:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@voucher.purchase_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\SmartcardRedemptionFixtures:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@smartcard_service"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\VoucherRedemptionFixtures:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@voucher.voucher_service"
        tags:
            - { name: doctrine.fixture.orm }
    
    CommonBundle\DataFixtures\OrganizationFixtures:
        arguments:
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\ServiceFixtures:
        arguments:
        - "@fos_user.user_manager"
        - "@security.encoder_factory"
        tags:
        - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\SmartcardFixtures:
        arguments:
            - "@=service('kernel').getEnvironment()"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\TransactionFixtures:
        arguments:
            - "@=service('kernel').getEnvironment()"
            - "@transaction.khm_financial_provider"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\ProductFixtures:
        arguments:
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }

    CommonBundle\DataFixtures\VendorFixtures:
        arguments:
            - "@kernel"
        tags:
            - { name: doctrine.fixture.orm }



#######################################################################################
##                                       VOTER                                       ##
#######################################################################################

    voter_default:
        class: CommonBundle\Voter\DefaultVoter
        arguments:
            - "@security.role_hierarchy"
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - "@logger"
        tags:
            - { name: security.voter }

    voter_project:
        class: CommonBundle\Voter\ProjectVoter
        arguments:
            - "@security.role_hierarchy"
            - "@doctrine.orm.entity_manager"
            - "@logger"
        tags:
            - { name: security.voter }

#######################################################################################
##                                       EXPORT                                      ##
#######################################################################################

    CommonBundle\Utils\ExportService:
        class: CommonBundle\Utils\ExportService
        autowire: true
        public: true
