services:
    transaction.transaction_service:
        class: TransactionBundle\Utils\TransactionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.default_financial_provider:
        class: TransactionBundle\Utils\Provider\DefaultFinancialProvider
        public: true
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.khm_financial_provider:
        class: TransactionBundle\Utils\Provider\KHMFinancialProvider
        parent: transaction.default_financial_provider

    transaction.manual_bank_transfer:
        class: TransactionBundle\Service\ManualBankTransfer
        arguments: [ '@doctrine.orm.entity_manager' ]
        public: true
