services:
    transaction.transaction_service:
        class: TransactionBundle\Utils\TransactionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.default_financial_provider:
        class: TransactionBundle\Utils\Provider\DefaultFinancialProvider
        public: true
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.khm_financial_provider:
        class: TransactionBundle\Utils\Provider\KHMFinancialProvider
        parent: transaction.default_financial_provider

    TransactionBundle\Mapper\TransactionMapper:
        arguments:
            - "@serializer"
        public: true

    export.spreadsheet:
        class: TransactionBundle\Export\AssistanceSpreadsheetExport
        arguments: [ '@translator' ]
        public: true

    export.pdf:
        class: TransactionBundle\Export\AssistancePdfExport
        arguments: [ '@translator', '@templating', '@pdf_service' ]
        public: true
