services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewApiBundle\Serializer\MapperNormalizer:
        tags: [ 'serializer.normalizer' ]

    NewApiBundle\Mapper\:
        resource: '../../Mapper'
        tags: [ 'app.mapper' ]

    NewApiBundle\Controller\AssistanceController:

    NewApiBundle\Controller\SectorsCodelistController:
        arguments:
            - "@project.sector_service"

    NewApiBundle\Controller\BeneficiaryCodelistController:
        arguments:
            - "@doctrine.orm.entity_manager"
            -
    NewApiBundle\Request\ParamConverter\:
        resource: '../../Request/ParamConverter'
        tags: [ 'request.param_converter' ]

    NewApiBundle\Listener\ErrorResponseListener:
        arguments: [ '%kernel.debug%' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -100 }
