services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewApiBundle\Serializer\MapperNormalizer:
        tags: [ 'serializer.normalizer' ]

    NewApiBundle\Mapper\:
        resource: '../../Mapper'
        tags: [ 'app.mapper' ]

    NewApiBundle\Controller\AssistanceController:

    NewApiBundle\Controller\SectorsCodelistController:
        arguments:
            - "@project.sector_service"

    NewApiBundle\Controller\BeneficiaryCodelistController:
        arguments:
            - "@doctrine.orm.entity_manager"
            -
    NewApiBundle\Request\ParamConverter\PaginationConverter:
        tags: [ 'request.param_converter' ]
