services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewApiBundle\OutputType\:
        resource: '../../OutputType'

    NewApiBundle\Controller\AssistanceController:

    NewApiBundle\Controller\SectorsCodelistController:
        arguments:
            - "@project.sector_service"

    NewApiBundle\Serializer\OutputTypeNormalizer:
        calls:
            - [ 'registerOutputType', [ '@NewApiBundle\OutputType\AssistanceOutputType' ] ]
        tags: [ 'serializer.normalizer' ]
