services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NewApiBundle\Mapper\AssistanceMapper:

  NewApiBundle\Controller\AssistanceController:

  NewApiBundle\Controller\SectorsCodelistController:
    arguments:
      - "@project.sector_service"
