services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    VoucherBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    VoucherBundle\Utils\:
        resource: '../../Utils'
        autowire: true
        public: true

    voucher.booklet_service:
        alias: VoucherBundle\Utils\BookletService
        public: true

    voucher.product_service:
        alias: VoucherBundle\Utils\ProductService

    common.upload_service:
        class: CommonBundle\Utils\UploadService
        arguments: ['%aws_access_key_id%', '%aws_secret_access_key%', '%aws_s3_region%', '@service_container' ]
        public: true

    voucher.purchase_service:
        class: VoucherBundle\Model\PurchaseService
        public: true
        arguments: [ '@doctrine.orm.entity_manager' ]

    VoucherBundle\Mapper\SmartcardMapper:
        public: true

    VoucherBundle\Mapper\BookletMapper:
        arguments:
            - "@serializer"
        public: true

    VoucherBundle\Mapper\VoucherRedemptionBatchMapper:
        tags: [ 'app.mapper' ]
