services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    VoucherBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    VoucherBundle\Utils\:
        resource: '../../Utils'
        public: true

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    Knp\Bundle\GaufretteBundle\FilesystemMap:
        alias: knp_gaufrette.filesystem_map

    voucher.product_service:
        alias: VoucherBundle\Utils\ProductService

    common.upload_service:
        alias: CommonBundle\Utils\UploadService

    CommonBundle\Utils\UploadService:
        arguments: [ '%aws_access_key_id%', '%aws_secret_access_key%', '%aws_s3_region%', '@service_container' ]
        public: true

    VoucherBundle\Model\PurchaseService:
        public: true

    VoucherBundle\Mapper\SmartcardMapper:
        public: true

    VoucherBundle\Mapper\BookletMapper:
        public: true

    VoucherBundle\Mapper\VoucherRedemptionBatchMapper:
        tags: [ 'app.mapper' ]
