services:

    VoucherBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        public: true
        tags:
            - { name: 'app.controller' }

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    VoucherBundle\Utils\VendorService:
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@location_service', '@service_container']
        public: true

    voucher.booklet_service:
        alias: VoucherBundle\Utils\BookletService
        public: true

    VoucherBundle\Utils\BookletService:
        autowire: true
        public: true

    VoucherBundle\Utils\VoucherService:
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@service_container']
        public: true

    voucher.product_service:
        class: VoucherBundle\Utils\ProductService
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@service_container']
        public: true

    common.upload_service:
        class: CommonBundle\Utils\UploadService
        arguments: ['%aws_access_key_id%', '%aws_secret_access_key%', '%aws_s3_region%', '@service_container' ]
        public: true

    voucher.purchase_service:
        class: VoucherBundle\Model\PurchaseService
        public: true
        arguments: [ '@doctrine.orm.entity_manager' ]

    VoucherBundle\Mapper\SmartcardMapper:
        public: true

    VoucherBundle\Mapper\BookletMapper:
        arguments:
            - "@serializer"
        public: true

    VoucherBundle\Mapper\VoucherRedemptionBatchMapper:
        tags: [ 'app.mapper' ]
