services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ReportingBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    ReportingBundle\Utils\:
        resource: '../../Utils'

    reporting.reporting_service:
        alias: ReportingBundle\Utils\ReportingService
        public: true

    reporting.code_indicator_command:
        class: ReportingBundle\Command\ReportingCodeIndicatorAddCommand
        public: true
        tags:
            - { name: 'console.command' }

    reporting.data_indicator_command:
        class: ReportingBundle\Command\ReportingDataIndicatorAddCommand
        public: true
        tags:
            - { name: 'console.command' }

    ############################### Data Fillers ###############################

    reporting.data_fillers.reference:
        alias: ReportingBundle\Utils\DataFillers\DataFillersIndicator
        public: true

    reporting.data_fillers.default:
        alias: ReportingBundle\Utils\DataFillers\DataFillers
        public: true

    reporting.data_fillers.country:
        alias: ReportingBundle\Utils\DataFillers\Country\DataFillersCountry
        public: true

    reporting.data_fillers.project:
        alias: ReportingBundle\Utils\DataFillers\Project\DataFillersProject
        public: true

    reporting.data_fillers.distribution:
        alias: ReportingBundle\Utils\DataFillers\Distribution\DataFillersDistribution
        public: true

    ################################## Computers ##################################

    reporting.computer:
        alias: ReportingBundle\Utils\Computers\Computer

    ############################### Data Retrievers ###############################

    reporting.data_retrievers.country:
        alias: ReportingBundle\Utils\DataRetrievers\CountryDataRetriever
        public: true

    reporting.data_retrievers.project:
        alias: ReportingBundle\Utils\DataRetrievers\ProjectDataRetriever
        public: true

    reporting.data_retrievers.distribution:
        alias: ReportingBundle\Utils\DataRetrievers\AssistanceRetriever
        public: true

    ################################## Formatters ##################################

    reporting.formatter:
        alias: ReportingBundle\Utils\Formatters\Formatter

    ################################## Finders ##################################

    reporting.finder:
        alias: ReportingBundle\Utils\Finders\Finder
