services:


#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    distribution.distribution_service:
        class: DistributionBundle\Utils\DistributionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@serializer'
            - '@validator'
            - '@location_service'
            - '@distribution.commodity_service'
            - '@distribution.configuration_loader'
            - '@distribution.criteria_distribution_service'
            - '%distribution.retriever%'
            - '@service_container'

    distribution.distribution_beneficiary_service:
        class: DistributionBundle\Utils\DistributionBeneficiaryService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@serializer'
            - '@validator'
            - '@service_container'

    distribution.criteria_distribution_service:
        class: DistributionBundle\Utils\CriteriaDistributionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@distribution.configuration_loader'
            - '@beneficiary.vulnerability_resolver'
            - '@serializer'

    distribution.configuration_loader:
        class: DistributionBundle\Utils\ConfigurationLoader
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%distribution.criteria%'

    distribution.modality_service:
        class: DistributionBundle\Utils\ModalityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    distribution.commodity_service:
        class: DistributionBundle\Utils\CommodityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    DistributionBundle\Mapper\AssistanceBeneficiaryMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\BeneficiaryMapper"
        public: true

    DistributionBundle\Mapper\AssistanceCommunityMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\CommunityMapper"
        public: true

    DistributionBundle\Mapper\AssistanceInstitutionMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\InstitutionMapper"
        public: true

    DistributionBundle\Mapper\CampMapper:
        public: true

    DistributionBundle\Mapper\GeneralReliefItemMapper:
        arguments:
            - "@serializer"
        public: true

    DistributionBundle\Mapper\CampMapper:
        public: true

#######################################################################################
##                                       CSV                                         ##
#######################################################################################

    distribution.distribution_csv_service:
        class: DistributionBundle\Utils\DistributionCSVService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@beneficiary.household_export_csv_service'
            - '@service_container'
            - '@beneficiary.household_service'
            - '@serializer'
            - '@validator'
            - "@request_validator"
            - "@beneficiary.csv_to_array_mapper"

    distribution.export.smartcard_invoice:
        class: DistributionBundle\Export\SmartcardInvoiceExport
        public: true
