services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DistributionBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    DistributionBundle\Utils\:
        resource: '../../Utils'
        public: true

    DistributionBundle\Extension\BeneficiaryGenderExtension:
        tags:
            - { name: twig.extension }

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    DistributionBundle\Controller\AssistanceController:
        autowire: true
        public: true
        arguments:
            - '@serializer'
            - '@DistributionBundle\Utils\AssistanceBeneficiaryService'
            - '@DistributionBundle\Utils\AssistanceService'
            - '@DistributionBundle\Mapper\AssistanceBeneficiaryMapper'
            - '@DistributionBundle\Mapper\AssistanceCommunityMapper'
            - '@DistributionBundle\Mapper\AssistanceInstitutionMapper'
            - '@distribution.distribution_csv_service'
            - '@BeneficiaryBundle\Mapper\AssistanceMapper'

    distribution.assistance_service:
        alias: DistributionBundle\Utils\AssistanceService
        public: true

    DistributionBundle\Utils\AssistanceService:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@serializer'
            - '@validator'
            - '@CommonBundle\Utils\LocationService'
            - '@distribution.commodity_service'
            - '@distribution.configuration_loader'
            - '@DistributionBundle\Utils\CriteriaAssistanceService'
            - '%distribution.retriever%'
            - '@service_container'

    distribution.configuration_loader:
        alias: DistributionBundle\Utils\ConfigurationLoader
        public: true

    DistributionBundle\Utils\ConfigurationLoader:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%distribution.criteria%'

    distribution.commodity_service:
        alias: DistributionBundle\Utils\CommodityService
        public: true

    DistributionBundle\Mapper\AssistanceBeneficiaryMapper:
        public: true

    DistributionBundle\Mapper\AssistanceCommunityMapper:
        public: true

    DistributionBundle\Mapper\AssistanceInstitutionMapper:
        public: true

    DistributionBundle\Mapper\CampMapper:
        public: true

    DistributionBundle\Mapper\GeneralReliefItemMapper:
        public: true

#######################################################################################
##                                       CSV                                         ##
#######################################################################################

    distribution.distribution_csv_service:
        alias: DistributionBundle\Utils\DistributionCSVService
        public: true

    DistributionBundle\Export\SmartcardExport:
        arguments:
            - '@CommonBundle\Utils\ExportService'
            - '@doctrine.orm.entity_manager'
            - '@templating'
            - '@pdf_service'

    distribution.export.smartcard:
        alias: DistributionBundle\Export\SmartcardExport
        public: true

    distribution.export.smartcard_invoice:
        class: DistributionBundle\Export\SmartcardInvoiceExport
        public: true
