services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ProjectBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    ProjectBundle\Utils\:
        resource: '../../Utils'

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    ProjectBundle\Mapper\ProjectMapper:
        public: true

    ProjectBundle\Mapper\DonorMapper:
        public: true

    ProjectBundle\Mapper\SectorMapper:
        public: true

    project.sector_mapper:
        class: ProjectBundle\Mapper\SectorMapper
        arguments: []
        public: true
