services:


#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    project.project_service:
        class: ProjectBundle\Utils\ProjectService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator' , '@service_container']
        public: true

    project.donor_service:
        class: ProjectBundle\Utils\DonorService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator', '@service_container']
        public: true

    project.sector_service:
        class: ProjectBundle\Utils\SectorService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator']
        public: true
